version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: lakehouse_minio_v2
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # NEW: Your Streamlit application
  dashboard:
    build: .
    container_name: lakehouse_ui
    ports:
      - "8501:8501"
    environment:
      - MINIO_ENDPOINT=minio:9000  # <--- NOTE: You're no longer using 'localhost'
    volumes:
      - .:/app  # This allows you to see changes made in Windows code reflected in Docker
    command: sh entrypoint.sh
    depends_on:
      - minio

volumes:
  minio_data: